import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:guix/src/config/guix_config.dart';
import 'package:guix/src/commands/sync_command.dart';

/// Generate the content of a fetch-flutter.sh script from [config].
///
/// The generated script detects the host architecture at runtime and builds
/// the correct archive name (e.g. `flutter_linux_3.24.5-stable.tar.xz` for
/// x86_64, `flutter_linux_arm64_3.24.5-stable.tar.xz` for aarch64), matching
/// the naming convention used by the standalone guix-standalone-scripts.
String generateFetchFlutterScript(GuixConfig config) {
  return '''#!/usr/bin/env bash
# Generated by: guix_dart eject
# Fetches Flutter SDK ${config.flutter.version}
set -euo pipefail

FLUTTER_VERSION="${config.flutter.version}"
FLUTTER_CHANNEL="${config.flutter.channel}"
SDK_DIR=".flutter-sdk/flutter"

if [ -d "\$SDK_DIR" ] && [ -f "\$SDK_DIR/version" ]; then
  CURRENT=\$(cat "\$SDK_DIR/version" | tr -d '\\n')
  if [ "\$CURRENT" = "\$FLUTTER_VERSION" ]; then
    echo "Flutter \$FLUTTER_VERSION already present."
    exit 0
  fi
fi

case "\$(uname -m)" in
  aarch64|arm64) ARCH="_arm64" ;;
  *)             ARCH="" ;;
esac

ARCHIVE="flutter_linux\${ARCH}_\${FLUTTER_VERSION}-\${FLUTTER_CHANNEL}.tar.xz"
URL="https://storage.googleapis.com/flutter_infra_release/releases/\$FLUTTER_CHANNEL/linux/\$ARCHIVE"

echo "Downloading Flutter \$FLUTTER_VERSION..."
mkdir -p .flutter-sdk
curl -fLO --output-dir .flutter-sdk "\$URL"

echo "Extracting..."
rm -rf "\$SDK_DIR"
tar xf ".flutter-sdk/\$ARCHIVE" -C .flutter-sdk/
rm ".flutter-sdk/\$ARCHIVE"

echo "Flutter \$FLUTTER_VERSION ready at \$SDK_DIR"
''';
}

class EjectCommand extends Command<int> {
  @override
  final String name = 'eject';

  @override
  final String description = 'Generate standalone shell scripts from config.';

  EjectCommand() {
    argParser
      ..addOption('dir', abbr: 'd', defaultsTo: 'scripts', help: 'Output directory for scripts');
  }

  @override
  Future<int> run() async {
    final outputDir = argResults!['dir'] as String;
    final config = GuixConfig.load();

    final dir = Directory(outputDir);
    if (!dir.existsSync()) dir.createSync(recursive: true);

    var count = 0;

    // Generate fetch-flutter.sh
    _writeScript('$outputDir/fetch-flutter.sh', _generateFetchFlutter(config));
    count++;

    // Generate per-platform scripts
    for (final entry in config.platforms.entries) {
      final name = entry.key;
      final platform = entry.value;

      _writeScript('$outputDir/shell-$name.sh', _generateShellScript(config, name, platform));
      count++;

      _writeScript('$outputDir/build-$name.sh', _generateBuildScript(config, name, platform));
      count++;
    }

    // Generate Makefile
    _writeFile('$outputDir/../Makefile.generated', _generateMakefile(config, outputDir));
    count++;

    // Write .env files so the ejected project is self-contained for
    // standalone script users without requiring guix_dart going forward.
    writeEnvFiles(config);

    print('Ejected $count files to $outputDir/');
    print('Generated Makefile.generated');
    print('');
    print('These scripts are self-contained and do not depend on guix_dart.');
    return 0;
  }

  void _writeScript(String path, String content) {
    final file = File(path);
    file.writeAsStringSync(content);
    // Make executable
    Process.runSync('chmod', ['+x', path]);
    print('  wrote $path');
  }

  void _writeFile(String path, String content) {
    File(path).writeAsStringSync(content);
    print('  wrote $path');
  }

  String _generateFetchFlutter(GuixConfig config) =>
      generateFetchFlutterScript(config);

  String _generateShellScript(GuixConfig config, String name, PlatformConfig platform) {
    final envExports = platform.env.entries.map((e) => '${e.key}=${e.value}').join(' ');
    return '''#!/usr/bin/env bash
# Generated by: guix_dart eject
# Interactive $name development shell
set -euo pipefail

PINNED="\${1:-}"
FLUTTER_SDK="\$(pwd)/.flutter-sdk/flutter"

if [ ! -d "\$FLUTTER_SDK" ]; then
  echo "Flutter SDK not found. Run: ./\$(dirname "\$0")/fetch-flutter.sh"
  exit 1
fi

if [ "\$PINNED" = "--pinned" ]; then
  GUIX_CMD="guix time-machine -C ${config.channelsPath} -- shell -m ${platform.manifest}"
else
  GUIX_CMD="guix shell -m ${platform.manifest}"
fi

echo "Entering $name shell\${PINNED:+ (pinned)}..."
exec \$GUIX_CMD -- env \\
  $envExports \\
  FLUTTER_ROOT="\$FLUTTER_SDK" \\
  PATH="\$FLUTTER_SDK/bin:\$PATH" \\
  bash
''';
  }

  String _generateBuildScript(GuixConfig config, String name, PlatformConfig platform) {
    final envExports = platform.env.entries.map((e) => '${e.key}=${e.value}').join(' ');

    return '''#!/usr/bin/env bash
# Generated by: guix_dart eject
# Non-interactive $name build (CI-safe)
set -euo pipefail

PINNED="\${1:-}"
FLUTTER_SDK="\$(pwd)/.flutter-sdk/flutter"

if [ ! -d "\$FLUTTER_SDK" ]; then
  echo "Flutter SDK not found. Run: ./\$(dirname "\$0")/fetch-flutter.sh"
  exit 1
fi

if [ "\$PINNED" = "--pinned" ] || [ -z "\$PINNED" ]; then
  GUIX_CMD="guix time-machine -C ${config.channelsPath} -- shell -m ${platform.manifest}"
else
  GUIX_CMD="guix shell -m ${platform.manifest}"
fi

echo "Building $name..."
\$GUIX_CMD -- env \\
  $envExports \\
  FLUTTER_ROOT="\$FLUTTER_SDK" \\
  PATH="\$FLUTTER_SDK/bin:\$PATH" \\
  bash -c 'flutter pub get && ${platform.buildCommand}'

echo "Build complete: ${platform.buildOutput}"
''';
  }

  String _generateMakefile(GuixConfig config, String scriptDir) {
    final buf = StringBuffer();
    buf.writeln('# Generated by: guix_dart eject');
    buf.writeln('# Self-contained Makefile: does not depend on guix_dart');
    buf.writeln('');
    buf.writeln('.PHONY: setup clean');
    buf.writeln('');
    buf.writeln('setup:');
    buf.writeln('\t./$scriptDir/fetch-flutter.sh');
    buf.writeln('');

    for (final name in config.platformNames) {
      buf.writeln('.PHONY: shell-$name shell-$name-pinned build-$name build-$name-fast');
      buf.writeln('');
      buf.writeln('shell-$name:');
      buf.writeln('\t./$scriptDir/shell-$name.sh');
      buf.writeln('');
      buf.writeln('shell-$name-pinned:');
      buf.writeln('\t./$scriptDir/shell-$name.sh --pinned');
      buf.writeln('');
      buf.writeln('build-$name:');
      buf.writeln('\t./$scriptDir/build-$name.sh --pinned');
      buf.writeln('');
      buf.writeln('build-$name-fast:');
      buf.writeln('\t./$scriptDir/build-$name.sh --fast');
      buf.writeln('');
    }

    buf.writeln('clean:');
    buf.writeln('\trm -rf .flutter-sdk .android-sdk build/');

    return buf.toString();
  }
}
