name: guix_example
description: "Hash-verified Flutter example for the guix repository."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
