/// Guix manifest template for Android Flutter development.
const String androidManifestTemplate = r'''
;; Android build dependencies for Flutter
;; Generated by: guix_dart init
;; Provides JDK and TLS certs needed by sdkmanager and Gradle.

(specifications->manifest
  '(;; Core tools
    "git" "curl" "unzip" "xz" "which" "coreutils" "bash"

    ;; TLS certificates (required for sdkmanager in Guix shells)
    "nss-certs"

    ;; Java (required by Gradle and Android SDK tools)
    "openjdk@17"))
''';
