/// Guix manifest template for Linux/GTK Flutter development.
const String linuxManifestTemplate = r'''
;; Linux/GTK build dependencies for Flutter
;; Generated by: guix_dart init
;; Customize as needed.

(specifications->manifest
  '(;; Core tools
    "git" "curl" "unzip" "xz" "which" "coreutils" "bash"

    ;; C/C++ toolchain (Flutter Linux uses clang)
    "clang-toolchain"
    "gcc-toolchain@13"
    "cmake" "ninja" "pkg-config"

    ;; GTK 3
    "gtk+" "glib" "pango" "cairo" "gdk-pixbuf" "harfbuzz"

    ;; OpenGL / EGL
    "mesa" "libepoxy"

    ;; Fonts
    "fontconfig" "freetype"

    ;; Accessibility
    "at-spi2-core"

    ;; X11
    "libx11" "libxext" "libxrandr" "libxcursor" "libxfixes"
    "libxi" "libxinerama" "libxcomposite" "libxdamage"
    "libxrender" "libxtst"

    ;; Wayland
    "libxkbcommon"

    ;; System
    "zlib" "dbus"))
''';
