import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:guix/src/templates/config_template.dart';
import 'package:guix/src/templates/linux_manifest.dart';
import 'package:guix/src/templates/android_manifest.dart';
import 'package:yaml/yaml.dart';

void main() {
  group('init linux: config generation', () {
    test('generates guix.yaml with linux platform section', () {
      final yaml = generateConfig(projectName: 'my_app', platforms: ['linux']);
      expect(yaml, contains('linux:'));
      expect(yaml, contains('manifest: guix/linux.scm'));
      expect(yaml, contains('flutter build linux --release'));
      expect(yaml, isNot(contains('android:')));
    });

    test('generated yaml is parseable and has correct project name', () {
      final content =
          generateConfig(projectName: 'test_project', platforms: ['linux']);
      final parsed = loadYaml(content) as YamlMap;
      expect(parsed['project']['name'], 'test_project');
      expect(parsed['flutter']['version'], '3.24.5');
      expect(parsed['flutter']['channel'], 'stable');
      expect(parsed['platforms']['linux'], isNotNull);
    });
  });

  group('init android: config generation', () {
    test('generates guix.yaml with android platform section and sdk config',
        () {
      final yaml =
          generateConfig(projectName: 'my_app', platforms: ['android']);
      expect(yaml, contains('android:'));
      expect(yaml, contains('manifest: guix/android.scm'));
      expect(yaml, contains('flutter build apk --release'));
      expect(yaml, contains('cmdline_tools_build:'));
      expect(yaml, contains('platform_version:'));
      expect(yaml, contains('build_tools_version:'));
      expect(yaml, contains('ndk_version:'));
      expect(yaml, isNot(contains('linux:')));
    });

    test('android config includes custom sdk values', () {
      final yaml = generateConfig(
        projectName: 'my_app',
        platforms: ['android'],
        cmdlineToolsBuild: '99999',
        platformVersion: 'android-35',
        buildToolsVersion: '35.0.0',
        ndkVersion: '25.0.0',
      );
      expect(yaml, contains('cmdline_tools_build: "99999"'));
      expect(yaml, contains('platform_version: android-35'));
      expect(yaml, contains('build_tools_version: "35.0.0"'));
      expect(yaml, contains('ndk_version: "25.0.0"'));
    });
  });

  group('init linux android: multi-platform config generation', () {
    test('generates both linux and android sections', () {
      final yaml = generateConfig(
          projectName: 'my_app', platforms: ['linux', 'android']);
      expect(yaml, contains('linux:'));
      expect(yaml, contains('manifest: guix/linux.scm'));
      expect(yaml, contains('android:'));
      expect(yaml, contains('manifest: guix/android.scm'));
    });

    test('parsed yaml contains both platforms', () {
      final content = generateConfig(
          projectName: 'dual_app', platforms: ['linux', 'android']);
      final parsed = loadYaml(content) as YamlMap;
      final platforms = parsed['platforms'] as YamlMap;
      expect(platforms.containsKey('linux'), isTrue);
      expect(platforms.containsKey('android'), isTrue);
    });
  });

  group('manifest file content', () {
    test('linux manifest contains GTK and clang dependencies', () {
      expect(linuxManifestTemplate, contains('specifications->manifest'));
      expect(linuxManifestTemplate, contains('clang-toolchain'));
      expect(linuxManifestTemplate, contains('gtk+'));
      expect(linuxManifestTemplate, contains('cmake'));
      expect(linuxManifestTemplate, contains('ninja'));
      expect(linuxManifestTemplate, contains('pkg-config'));
    });

    test('linux manifest contains X11 and Wayland deps', () {
      expect(linuxManifestTemplate, contains('libx11'));
      expect(linuxManifestTemplate, contains('libxkbcommon'));
    });

    test('linux manifest header mentions guix_dart init', () {
      expect(linuxManifestTemplate, contains('Generated by: guix_dart init'));
    });

    test('android manifest contains JDK and nss-certs', () {
      expect(androidManifestTemplate, contains('specifications->manifest'));
      expect(androidManifestTemplate, contains('openjdk@17'));
      expect(androidManifestTemplate, contains('nss-certs'));
    });

    test('android manifest header mentions guix_dart init', () {
      expect(
          androidManifestTemplate, contains('Generated by: guix_dart init'));
    });
  });

  group('init file writing with temp directory', () {
    late Directory tmp;

    setUp(() {
      tmp = Directory.systemTemp.createTempSync('init_test_');
    });

    tearDown(() {
      tmp.deleteSync(recursive: true);
    });

    test('writes guix.yaml with linux config to disk', () {
      final content =
          generateConfig(projectName: 'disk_test', platforms: ['linux']);
      final configPath = p.join(tmp.path, 'guix.yaml');
      File(configPath).writeAsStringSync(content);
      expect(File(configPath).existsSync(), isTrue);
      final read = File(configPath).readAsStringSync();
      expect(read, contains('name: disk_test'));
      expect(read, contains('linux:'));
    });

    test('writes manifest files to guix/ directory', () {
      final guixDir = p.join(tmp.path, 'guix');
      Directory(guixDir).createSync();
      File(p.join(guixDir, 'linux.scm'))
          .writeAsStringSync(linuxManifestTemplate);
      File(p.join(guixDir, 'android.scm'))
          .writeAsStringSync(androidManifestTemplate);

      expect(File(p.join(guixDir, 'linux.scm')).existsSync(), isTrue);
      expect(File(p.join(guixDir, 'android.scm')).existsSync(), isTrue);

      final linuxContent =
          File(p.join(guixDir, 'linux.scm')).readAsStringSync();
      expect(linuxContent, contains('clang-toolchain'));

      final androidContent =
          File(p.join(guixDir, 'android.scm')).readAsStringSync();
      expect(androidContent, contains('openjdk@17'));
    });

    test('--force: overwrites existing guix.yaml', () {
      final configPath = p.join(tmp.path, 'guix.yaml');
      // Write initial file
      final initial =
          generateConfig(projectName: 'old_name', platforms: ['linux']);
      File(configPath).writeAsStringSync(initial);
      expect(File(configPath).readAsStringSync(), contains('old_name'));

      // Overwrite (simulating --force behavior)
      final updated =
          generateConfig(projectName: 'new_name', platforms: ['android']);
      File(configPath).writeAsStringSync(updated);
      final content = File(configPath).readAsStringSync();
      expect(content, contains('new_name'));
      expect(content, contains('android:'));
      expect(content, isNot(contains('old_name')));
    });

    test('--force: overwrites existing manifest files', () {
      final guixDir = p.join(tmp.path, 'guix');
      Directory(guixDir).createSync();
      final manifestPath = p.join(guixDir, 'linux.scm');
      File(manifestPath).writeAsStringSync('old content');

      // Overwrite (simulating --force behavior)
      File(manifestPath).writeAsStringSync(linuxManifestTemplate);
      final content = File(manifestPath).readAsStringSync();
      expect(content, contains('clang-toolchain'));
      expect(content, isNot(contains('old content')));
    });

    test('without --force: existing files are not overwritten', () {
      final configPath = p.join(tmp.path, 'guix.yaml');
      // Simulate the no-force check from InitCommand.run()
      File(configPath).writeAsStringSync('original');
      final configFile = File(configPath);
      final force = false;

      if (configFile.existsSync() && !force) {
        // Skip writing - this is the expected path
      } else {
        configFile.writeAsStringSync(
            generateConfig(projectName: 'x', platforms: ['linux']));
      }

      expect(File(configPath).readAsStringSync(), 'original');
    });
  });

  group('--from-existing: env file parsing', () {
    late Directory tmp;

    setUp(() {
      tmp = Directory.systemTemp.createTempSync('init_from_existing_test_');
    });

    tearDown(() {
      tmp.deleteSync(recursive: true);
    });

    test('parses flutter_version.env values into config', () {
      // Create a mock flutter_version.env
      File(p.join(tmp.path, 'flutter_version.env')).writeAsStringSync('''
FLUTTER_VERSION="3.27.1"
FLUTTER_CHANNEL="beta"
FLUTTER_SHA256_X64="abc123"
FLUTTER_SHA256_ARM64="def456"
''');

      // Simulate _initFromExisting parsing logic
      var flutterVersion = '3.24.5';
      var flutterChannel = 'stable';
      var checksumX64 = '';
      var checksumArm64 = '';

      final lines = File(p.join(tmp.path, 'flutter_version.env'))
          .readAsLinesSync();
      for (final line in lines) {
        _parseEnvLine(line, 'FLUTTER_VERSION', (v) => flutterVersion = v);
        _parseEnvLine(line, 'FLUTTER_CHANNEL', (v) => flutterChannel = v);
        _parseEnvLine(line, 'FLUTTER_SHA256_X64', (v) => checksumX64 = v);
        _parseEnvLine(line, 'FLUTTER_SHA256_ARM64', (v) => checksumArm64 = v);
      }

      expect(flutterVersion, '3.27.1');
      expect(flutterChannel, 'beta');
      expect(checksumX64, 'abc123');
      expect(checksumArm64, 'def456');
    });

    test('parses android_sdk_version.env values', () {
      File(p.join(tmp.path, 'android_sdk_version.env')).writeAsStringSync('''
ANDROID_CMDLINE_TOOLS_BUILD="99887766"
ANDROID_CMDLINE_TOOLS_SHA256="sha256hash"
ANDROID_PLATFORM_VERSION="android-35"
ANDROID_BUILD_TOOLS_VERSION="35.0.0"
ANDROID_NDK_VERSION="25.2.9519653"
''');

      var cmdlineToolsBuild = '14742923';
      var cmdlineToolsSha256 = '';
      var platformVersion = 'android-34';
      var buildToolsVersion = '34.0.0';
      var ndkVersion = '23.1.7779620';

      final lines = File(p.join(tmp.path, 'android_sdk_version.env'))
          .readAsLinesSync();
      for (final line in lines) {
        _parseEnvLine(
            line, 'ANDROID_CMDLINE_TOOLS_BUILD', (v) => cmdlineToolsBuild = v);
        _parseEnvLine(line, 'ANDROID_CMDLINE_TOOLS_SHA256',
            (v) => cmdlineToolsSha256 = v);
        _parseEnvLine(
            line, 'ANDROID_PLATFORM_VERSION', (v) => platformVersion = v);
        _parseEnvLine(line, 'ANDROID_BUILD_TOOLS_VERSION',
            (v) => buildToolsVersion = v);
        _parseEnvLine(line, 'ANDROID_NDK_VERSION', (v) => ndkVersion = v);
      }

      expect(cmdlineToolsBuild, '99887766');
      expect(cmdlineToolsSha256, 'sha256hash');
      expect(platformVersion, 'android-35');
      expect(buildToolsVersion, '35.0.0');
      expect(ndkVersion, '25.2.9519653');
    });

    test('generates valid config from parsed env values', () {
      File(p.join(tmp.path, 'flutter_version.env')).writeAsStringSync('''
FLUTTER_VERSION="3.27.1"
FLUTTER_CHANNEL="beta"
FLUTTER_SHA256_X64="aaa"
FLUTTER_SHA256_ARM64="bbb"
''');

      File(p.join(tmp.path, 'android_sdk_version.env')).writeAsStringSync('''
ANDROID_CMDLINE_TOOLS_BUILD="99999"
ANDROID_PLATFORM_VERSION="android-35"
ANDROID_BUILD_TOOLS_VERSION="35.0.0"
ANDROID_NDK_VERSION="25.0.0"
''');

      // Simulate manifest detection
      final guixDir = p.join(tmp.path, 'guix');
      Directory(guixDir).createSync();
      File(p.join(guixDir, 'linux.scm'))
          .writeAsStringSync(linuxManifestTemplate);
      File(p.join(guixDir, 'android.scm'))
          .writeAsStringSync(androidManifestTemplate);

      final platforms = <String>[];
      if (File(p.join(guixDir, 'linux.scm')).existsSync()) {
        platforms.add('linux');
      }
      if (File(p.join(guixDir, 'android.scm')).existsSync()) {
        platforms.add('android');
      }

      final content = generateConfig(
        projectName: 'migrated_app',
        platforms: platforms,
        flutterVersion: '3.27.1',
        flutterChannel: 'beta',
        checksumX64: 'aaa',
        checksumArm64: 'bbb',
        cmdlineToolsBuild: '99999',
        platformVersion: 'android-35',
        buildToolsVersion: '35.0.0',
        ndkVersion: '25.0.0',
      );

      final parsed = loadYaml(content) as YamlMap;
      expect(parsed['flutter']['version'], '3.27.1');
      expect(parsed['flutter']['channel'], 'beta');
      expect(parsed['flutter']['checksums']['x86_64'], 'aaa');
      expect(parsed['flutter']['checksums']['aarch64'], 'bbb');
      expect(parsed['platforms']['linux'], isNotNull);
      expect(parsed['platforms']['android'], isNotNull);
      expect(parsed['platforms']['android']['sdk']['cmdline_tools_build'],
          '99999');
    });

    test('defaults are used when env files are absent', () {
      var flutterVersion = '3.24.5';
      var flutterChannel = 'stable';
      final platforms = <String>[];

      // No flutter_version.env, no manifests - defaults stay
      if (!File(p.join(tmp.path, 'flutter_version.env')).existsSync()) {
        // defaults stay
      }
      if (!File(p.join(tmp.path, 'guix', 'linux.scm')).existsSync() &&
          !File(p.join(tmp.path, 'guix', 'android.scm')).existsSync()) {
        platforms.add('linux'); // fallback
      }

      expect(flutterVersion, '3.24.5');
      expect(flutterChannel, 'stable');
      expect(platforms, ['linux']);
    });

    test('env lines without quotes are also parsed', () {
      var version = '';
      _parseEnvLine('FLUTTER_VERSION=3.27.1', 'FLUTTER_VERSION',
          (v) => version = v);
      expect(version, '3.27.1');
    });

    test('env lines with unrelated keys are ignored', () {
      var version = 'original';
      _parseEnvLine(
          'OTHER_KEY="value"', 'FLUTTER_VERSION', (v) => version = v);
      expect(version, 'original');
    });
  });
}

/// Mirror of InitCommand._parseEnvLine for testing.
void _parseEnvLine(String line, String key, void Function(String) setter) {
  final match = RegExp('^$key="?([^"]*)"?').firstMatch(line);
  if (match != null) setter(match.group(1)!);
}
